name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build app
        run: npm run build
        working-directory: frontend

      - name: Install electron-builder
        run: npm install electron-builder --no-save
        working-directory: frontend

      - name: Build installer
        run: npx electron-builder --win --x64
        working-directory: frontend
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: frontend/dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
